name: Mike's Action Runner

on: push

jobs:
  my-first-set-of-steps:
    runs-on: ubuntu-latest
    steps:
      - run: ls -al
      - run: echo "Hello, World!"
      - run: echo "This job was triggered by ${{ github.actor}}"
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "The event type that triggered this action was ${{ github.event_name }}."
      - run: echo "The commit message was ${{ github.event.head_commit.message }}."
      - uses: actions/checkout@v3
      - run: ls -al
      - run: node --version
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: node --version
      - name: Install NPM packages
        run: yarn install --frozen-lockfile
        
  write-back-to-repo:
    runs-on: ubuntu-latest
    needs: my-first-set-of-steps
    steps:
      - run: ls -al
      - uses: actions/checkout@v3
      - run: |
          echo "writing to file..."
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push      

