name: Mike's Action Runner

on: push

jobs:
  my-first-set-of-steps:
    runs-on: ubuntu-latest
    steps:
      - name: list dir
        run: ls -al
      - name: say hi
        run: echo "Hello, World!"
      - name: list github.actor
        run: echo "This job was triggered by ${{ github.actor}}"
      - name: list runner.os
        run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - name: list github.ref
        run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: list github.event_name
        run: echo "The event type that triggered this action was ${{ github.event_name }}."
      - name: list github.commit.message
        run: echo "The commit message was ${{ github.event.head_commit.message }}."
      - name: checkout repo code
        uses: actions/checkout@v3
      - name: list dir again
        run: ls -al
      - name: list node version
        run: node --version
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: list node version again
        run: node --version
      - name: Install NPM packages
        run: yarn install --frozen-lockfile
        
  write-back-to-repo:
    runs-on: ubuntu-latest
    needs: my-first-set-of-steps
    steps:
      - name: list dir
        run: ls -al
      - name: checkout repo code
        uses: actions/checkout@v3
      - name: write back to repo
        env:
          GITHUB_TOKEN:: ${{ secrets.GHP_TOKEN }}
        run: |
          echo "writing to file..."
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push      

